# Generated by Django 3.2 on 2022-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
