# Generated by Django 3.2 on 2022-05-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_painting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='isordered',
            field=models.BooleanField(default=False),
        ),
    ]
